### PR TITLE
Consts

### PR DESCRIPTION
**Pull request by nciric**
I don't like magic numbers 2, 3 and 8. Let me know if const section should go somewhere else.

Also parse_ and is_ methods look identical for attributes and types, but are also trivial so I didn't want to refactor them.

### CODE REVIEW

**Comment by zbraniecki** [comment]
I like it!

What do you think about using ranges here?

```rust
use std::ops::Range;
const TYPE_LENGTH: Range<usize> = 3..8;
```

And then in the code we can do:

```rust
fn parse_type(t: &[u8]) -> Result<Option<TinyStr8>, ParserError> {
    let s = TinyStr8::from_bytes(t).map_err(|_| ParserError::InvalidSubtag)?;
    if !TYPE_LENGTH.contains(t) || !.is_ascii_alphanumeric() {
        return Err(ParserError::InvalidSubtag);
    }

    let s = s.to_ascii_lowercase();
    if s == TRUE_TYPE {
        Ok(None)
    } else {
        Ok(Some(s))
    }
}
```

**Comment by nciric** [comment]
I was looking for it (new to Rust) - Range looks great. I'll make a fix.

**Comment by nciric** [comment]
Using RangeInclusive<> instead - PTAL.

**Comment by zbraniecki** [comment]
Looks great! Thank you!

**Pull request merged**
